require("core.plugin_config.colorscheme")
require("core.plugin_config.lsp")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.treesitter-context")
require("core.plugin_config.dap")
