#!/bin/bash

alias \
  vi='nvim' \
  vim='nvim' \
  sssh="~/Documents/projects/maya-gitlab/sssh/sssh.sh" \
  cp='cp -iv' \
  mv='mv -iv' \
  rm='rm -iv'

case "$(uname -s)" in
  "Linux") alias \
    pbcopy='xsel --clipboard --input' \
    pbpaste='xsel --clipboard --output' \
    ls='ls --color=auto'
  ;;
  "Darwin") alias \
    ls='ls -G'
  ;;
esac
